# Generated by Django 4.2.7 on 2025-05-14 18:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gitlab_classroom', '0016_remove_classroom_teacher_classroom_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='teacher',
        ),
        migrations.AddField(
            model_name='assignment',
            name='is_group',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assignment',
            name='teachers',
            field=models.ManyToManyField(related_name='assignment_teachers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_classroom', to='gitlab_classroom.classroom'),
        ),
    ]
