# Generated by Django 5.0.3 on 2025-05-18 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gitlab_classroom', '0018_assessment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='score',
            field=models.CharField(default='None', max_length=4),
        ),
    ]
