# Generated by Django 5.0.3 on 2025-06-20 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gitlab_classroom', '0020_groupproject'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupproject',
            name='assignment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='group_projects', to='gitlab_classroom.assignment'),
            preserve_default=False,
        ),
    ]
