# Generated by Django 5.0.3 on 2025-06-22 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gitlab_classroom', '0022_remove_groupproject_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupproject',
            name='gitlab_group_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='is_group',
            field=models.BooleanField(default=False),
        ),
    ]
